<?php
return [
  'NORGESPAKKE' => [
    'ProductCode'     => '3067',
    'ProductName'     => 'Norgespakke egenemballert',
    'DisplayName'     => 'På postkontor eller post i butikk (Norgespakke)',
    'DescriptionText' => 'Hentes på mottakers lokale postkontor/post i butikk.',
    'HelpText'        => 'Sendingen er en Norgespakke som blir levert til mottakers postkontor/ post i butikk. Mottaker varsles om at sendingen er ankommet via hentemelding i postkassen. Transporttid er normalt 2-3 virkedager, avhengig av strekning. Sendingen kan spores ved hjelp av sporingsnummeret.',
  ],
  'SERVICEPAKKE' => [
    'ProductCode'     => '1202',
    'ProductName'     => 'Klimanøytral Servicepakke',
    'DisplayName'     => 'På posten',
    'DescriptionText' => 'Hentes på mottakers lokale postkontor/post i butikk.',
    'HelpText'        => 'Sendingen er en Klimanøytral Servicepakke som blir levert til mottakers postkontor/ post i butikk. Mottaker kan velge å hente sendingen på et annet postkontor/post i butikk enn sitt lokale. Mottaker varsles om at sendingen er ankommet via SMS, e-post eller hentemelding i postkassen. Transporttid er normalt 1-3 virkedager, avhengig av strekning. Sendingen kan spores ved hjelp av sporingsnummeret.',
  ],
  'PA_DOREN' => [
    'ProductCode'     => '1736',
    'ProductName'     => 'På Døren',
    'DisplayName'     => 'Hjem på kvelden, 17-21',
    'DescriptionText' => 'Pakken leveres hjem til deg, sjåføren ringer 30 - 60 min. før ankomst',
    'HelpText'        => 'Sendingen leveres hjem til deg mellom klokken 17 og 21. Du varsles i god tid om forventet utleveringsdag på sms og/eller e-post, i tillegg til nytt varsel når sendingen er lastet på bil for utkjøring samme kveld. Sjåfør ringer deg på mobiltelefon 30 - 60 minutter før levering. Dersom sendingen ikke kan leveres, blir den fraktet til lokalt postkontor/ post i butikk og du vil motta en varsel om dette via SMS, e-post eller hentemelding i postkassen. Sendingen kan spores ved hjelp av sporingsnummeret.',
  ],
  'PAKKE_I_POSTKASSEN' => [
    'ProductCode'     => '3584',
    'ProductName'     => 'Pakke i postkassen',
    'DisplayName'     => 'Pakke i postkassen',
    'DescriptionText' => 'Pakken leveres i din postkasse innen 2 virkedager.',
    'HelpText'        => 'Pakke i postkassen leveres i mottakers postkasse, og er egnet for små og lette sendinger (maksimalt 2 kg). Dersom postkassen er låst eller full, blir pakken sendt til mottakers lokale hentested (postkontontor eller Post i Butikk).',
    'ProductLink'     => 'https://www.bring.no/sende/pakker/private-i-norge/pakke-i-postkassen',
  ],
  'BPAKKE_DOR-DOR' => [
    'ProductCode'     => '1000',
    'ProductName'     => 'Bedriftspakke',
    'DisplayName'     => 'På jobben, 08-16',
    'DescriptionText' => 'Leveres uten at sjåføren ringer først',
    'HelpText'        => 'Sendingen er en Bedriftspakke som leveres til mottakers arbeidssted mellom klokken 08 og 16. Bestiller du varsling, vil mottaker varsles når sendingen er lastet på bil for uttkjøring, via SMS og/eller e-post. Dersom sendingen ikke kan leveres, blir den fraktet til lokalt postkontor/ post i butikk. Mottaker varsles om dette via SMS, e-post eller hentemelding i postkassen. Sendingen kan spores ved hjelp av sporingssnummeret.',
  ],
  'EKSPRESS09' => [
    'ProductCode'     => '1002',
    'ProductName'     => 'Bedriftspakke Ekspress-Over natten',
    'DisplayName'     => 'Ekspress over natten',
    'DescriptionText' => 'Levering på dør vil skje påfølgende dag innen kl 1600 for dette postnummeret.',
    'HelpText'        => 'Levering hjem på dør før kl 0900 (til mindre steder normalt før kl 1600). Du kan varsles ved SMS/e-post, forutsatt at du har oppgitt telefonnummer/epostadresse ved bestilling. Sendingen kan spores ved hjelp av sporingsnummeret.',
  ],
  'EXPRESS_NORDIC_SAME_DAY' => [
    'ProductCode'     => '3336',
    'ProductName'     => 'Quickpack SameDay',
    'DisplayName'     => 'Omgående levering, dagtid og kveldstid',
    'DescriptionText' => 'Bud henter og leverer omgående til dør.',
    'HelpText'        => 'Når du trenger raskest mulig budlevering. Bring henter pakken omgående hos avsender og flyr den med første fly til mottaker. Innenfor Norden inkluderer produktet også forsikring av forsendelsen som dekker inntil NOK 100 000,- per sending.',
  ],
  'EXPRESS_INTERNATIONAL_0900' => [
    'ProductCode'     => '3337',
    'ProductName'     => 'Quickpack Over Night 0900',
    'DisplayName'     => 'Levering neste dag innen kl. 9',
    'DescriptionText' => 'Bud henter og leverer til dør.',
    'HelpText'        => 'Når du trenger raskest mulig budlevering. Bring henter pakken hos avsender og leverer den på dør til mottaker.',
  ],
  'EXPRESS_INTERNATIONAL_1200' => [
    'ProductCode'     => '3338',
    'ProductName'     => 'Quickpack Over Night 1200',
    'DisplayName'     => 'Levering neste dag innen kl. 12',
    'DescriptionText' => 'Bud henter og leverer til dør.',
    'HelpText'        => 'Når du trenger rask budlevering. Bring henter pakken hos avsender og leverer den på dør til mottaker.',
  ],
  'EXPRESS_INTERNATIONAL' => [
    'ProductCode'     => '3339',
    'ProductName'     => 'Quickpack Day Certain',
    'DisplayName'     => 'Levering neste dag',
    'DescriptionText' => 'Bud henter og leverer til dør.',
    'HelpText'        => 'Når du trenger en rask og rimelig budlevering. Bring henter pakken hos avsender og leverer den på dør til mottaker.',
  ],
  'EXPRESS_ECONOMY' => [
    'ProductCode'     => '3340',
    'ProductName'     => 'Quickpack Express Economy',
    'DisplayName'     => 'Levering tidligst neste dag kl. 17',
    'DescriptionText' => 'Bud henter og leverer til dør.',
    'HelpText'        => 'Når du trenger rimelig budlevering. Bring henter pakken hos avsender og leverer den på dør til mottaker.',
  ],
  'CARGO_GROUPAGE' => [
    'ProductCode'     => '3050',
    'ProductName'     => 'Cargo',
    'DisplayName'     => 'Cargo',
    'DescriptionText' => 'N/A',
    'HelpText'        => 'N/A',
  ],
  'BUSINESS_PARCEL' => [
    'ProductCode'     => '0330',
    'ProductName'     => 'CarryOn Business',
    'DisplayName'     => 'Til mottakers dør',
    'DescriptionText' => 'Pakke til bedrifter i utlandet',
    'HelpText'        => 'CarryOn Business er en enkelt og effektiv måte å sende pakker til andre firmaer i Norden og til resten av verden. Pakker hentes i henhold til avtale, og leveres til mottaker mellom mandag- fredag i kontortiden. I enkelte land leveres pakkene på mottakers postkontor.',
  ],
  'PICKUP_PARCEL' => [
    'ProductCode'     => '0340',
    'ProductName'     => 'CarryOn HomeShopping',
    'DisplayName'     => 'Till utlämningsställe',
    'DescriptionText' => 'Hentes på mottakers lokale utleveringssted i butikk.',
    'HelpText'        => 'Sendingen blir levert til mottakers nærmeste utleveringssted. Mottaker kan velge å hente sendingen på et annet postkontor/post i butikk enn sitt lokale. Mottaker varsles om at sendingen er ankommet via SMS, e-post eller hentemelding i postkassen. Sendingen kan spores ved hjelp av sporingsnummeret.',
  ],
  'COURIER_VIP' => [
    'ProductCode'     => 'VIP25',
    'ProductName'     => 'Bud VIP',
    'DisplayName'     => 'Omgående levering',
    'DescriptionText' => 'Leveres omgående av bud til dør.',
    'HelpText'        => 'Sending hentes hos avsender innen 10 minutter og leveres direkte til mottaker.',
  ],
  'COURIER_1H' => [
    'ProductCode'     => '1H25',
    'ProductName'     => 'Bud 1 time',
    'DisplayName'     => 'Levering innen 1 time',
    'DescriptionText' => 'Leveres innen 1 time av bud til dør.',
    'HelpText'        => 'Sending hentes hos avsender og leveres til mottaker innen 1 time.',
  ],
  'COURIER_2H' => [
    'ProductCode'     => '2H25',
    'ProductName'     => 'Bud 2 timer',
    'DisplayName'     => 'Levering innen 2 timer',
    'DescriptionText' => 'Leveres av bud til dør innen 2 timer.',
    'HelpText'        => 'Sending hentes hos avsender og leveres til mottaker innen 2 timer.',
  ],
  'COURIER_4H' => [
    'ProductCode'     => '4H25',
    'ProductName'     => 'Bud 4 timer',
    'DisplayName'     => 'Levering innen 4 timer',
    'DescriptionText' => 'Leveres av bud til dør innen 4 timer.',
    'HelpText'        => 'Sending hentes hos avsender og leveres til mottaker innen 4 timer.',
  ],
  'COURIER_6H' => [
    'ProductCode'     => '6H25',
    'ProductName'     => 'Bud 6 timer',
    'DisplayName'     => 'Levering innen 6 timer',
    'DescriptionText' => 'Leveres av bud til dør innen 6 timer.',
    'HelpText'        => 'Sending hentes hos avsender og leveres til mottaker innen 6 timer.',
  ],
  'OIL_EXPRESS' => [
    'ProductCode'     => '3050',
    'ProductName'     => 'OIL_EXPRESS',
    'DisplayName'     => 'Oil Express',
    'DescriptionText' => 'N/A',
    'HelpText'        => 'N/A',
  ]
];